on:
  workflow_call:
    
jobs:
  google-auth:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}