name: Deploy
on:
  workflow_run:
    workflows: [ Test ]
    types: [ completed ]
jobs:
  prod:
    if: ${{ (github.ref == 'refs/heads/main' || github.base_ref == 'main') && github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/_gcp-cloud-run-deploy.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: prod
      ref: ${{ github.sha }}
    secrets: inherit