name: Deploy

on:
  push:
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write
  id-token: write

jobs:
  prod:
    if: ${{ github.ref == 'refs/heads/main' || github.base_ref == 'main' }}
    uses: ./.github/workflows/_deployment.yml
    permissions: 
      id-token: write
      contents: read
    with:
      env: prod
      ref: ${{ github.sha }}
    secrets: inherit
    