name: Deploy

on:
  workflow_run:
    workflows: [ Test ]
    types: [ completed ]


permissions:
  contents: read
  actions: read
  checks: write
  id-token: write

jobs:
  prod:
    if: ${{ (github.ref == 'refs/heads/main' || github.base_ref == 'main') && github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/_deployment.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: prod
      ref: ${{ github.sha }}
    secrets: inherit
    